name: Publish REST API
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    environment:
      name: update
    steps:
    - uses: actions/checkout@v2
    - name: install dependences
      run: |
        sudo apt-get update -y
        sudo apt-get install ncftp -y
    - name: push
      run: |
        ncftpput -aR -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} ${{ secrets.SERVER }} ${{ secrets.API_URL }} bin/core
        ncftpput -a -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} ${{ secrets.SERVER }} ${{ secrets.API_URL }} bin/index.php
        ncftpput -a -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} ${{ secrets.SERVER }} ${{ secrets.API_URL }} bin/webhook.php
    - name: Set envirorment varible(s)
      run: |
        echo "::set-output name=PUSH_PATH::$(curl -sL https://api.github.com/repos/createstructure/rest-createstructure/releases/latest | jq -r '.upload_url')"
        echo "::set-output name=DB::db/database.sql"
      id: envirorment-variables
    - name: Upload database sql
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.envirorment-variables.outputs.PUSH_PATH }}
        asset_path: ${{ steps.envirorment-variables.outputs.DB }}
        asset_name: database.sql
        asset_content_type: application/zip
