name: Publish REST API
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    environment:
      name: update
    steps:
    - uses: actions/checkout@v2
    - name: install dependences
      run: |
        sudo apt-get update -y
        sudo apt-get install ncftp -y
    - name: push
      run: |
        ncftpput -aR -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} ${{ secrets.SERVER }} ${{ secrets.API_URL }} bin/core
        ncftpput -a -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} ${{ secrets.SERVER }} ${{ secrets.API_URL }} bin/index.php
        ncftpput -a -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} ${{ secrets.SERVER }} ${{ secrets.API_URL }} bin/webhook.php
